.\" Manpage for rldns.
.TH man 8 "11 July 2014" "1.0" "nrldns man page"
.SH NAME
rldns \- A simple free version of lightweight dns server for linux and bsd family
.SH VERSION
rldns version 1.1 - free version
.SH SYNOPSIS
rldns 
.SH DESCRIPTION
rldns-1.1 free version. 
.PP
rldns is a simple lightweight basic dns server for linux and bsd family, current version supports a name, c name, mx, ns requests. 
.PP
Additional feature : load balancing
.PP
rldns currently supports x86, x86_64 and arm architecture, supported operating system : linux, freebsd, netbsd and openbsd
.SH OPTIONS
rldns does not take any options.
.SH AUTHOR
Antonius (Ringlayer)
.PP
www.ringlayer.net
